#version 450

layout(local_size_x = WARP_SIZE) in;

layout(set = 0, binding = 0) restrict readonly buffer Input {
    uint in_array[];
};
layout(set = 0, binding = 1) restrict writeonly buffer Output {
    uint out_array[];
};

layout(push_constant) uniform Constants {
    uint start_in;
    uint count;
    uint start_out;
};

void main() {
    uint idx = gl_GlobalInvocationID.x;

    if (idx >= count) {
        return;
    }

    out_array[start_out + idx] = in_array[start_in + idx];
}
